// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWH0hrIynZqjqDDZk2vY33dDt0Ai1UGpE',
    appId: '1:378449916164:web:1183d9b633e30596dde051',
    messagingSenderId: '378449916164',
    projectId: 'attendence-929ab',
    authDomain: 'attendence-929ab.firebaseapp.com',
    storageBucket: 'attendence-929ab.appspot.com',
    measurementId: 'G-E8WKPQF03D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8l3QtjQi0HMB9HgnwTKud6BqRpqOobd4',
    appId: '1:378449916164:android:299fad793b51b4a4dde051',
    messagingSenderId: '378449916164',
    projectId: 'attendence-929ab',
    storageBucket: 'attendence-929ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBU5Coylxqgd1kx7R97YYr2xtW6mngpZ8',
    appId: '1:378449916164:ios:fe7a4cfffff282cadde051',
    messagingSenderId: '378449916164',
    projectId: 'attendence-929ab',
    storageBucket: 'attendence-929ab.appspot.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBU5Coylxqgd1kx7R97YYr2xtW6mngpZ8',
    appId: '1:378449916164:ios:7b82d6b3b9fe2e91dde051',
    messagingSenderId: '378449916164',
    projectId: 'attendence-929ab',
    storageBucket: 'attendence-929ab.appspot.com',
    iosBundleId: 'com.example.attendanceSystem.RunnerTests',
  );
}
